name: Go Build

on:
  push:
    branches: ["main"]
    tags: ["v*"]  # 添加 tag 触发
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Create Output Directory
        run: mkdir -p bin

      - name: Build Binaries
        run: |
          for arch in amd64 arm64; do
            GOOS=linux GOARCH=$arch go build -o "bin/dirstats-linux-$arch" ./cmd/dirstats/main.go
          done

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dirstats-binaries
          path: bin/*

      - name: Create Release
        id: create_release  # 添加 ID
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # 修改这里
          release_name: "Release ${{ github.ref_name }}"

      - name: Upload Release Assets (AMD64)
        uses: actions/upload-release-asset@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/dirstats-linux-amd64
          asset_name: dirstats-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Assets (ARM64)
        uses: actions/upload-release-asset@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/dirstats-linux-arm64
          asset_name: dirstats-linux-arm64
          asset_content_type: application/octet-stream
