name: Go Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"  # 替换为你的 Go 版本

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Create Output Directory
        run: mkdir -p bin  # 确保 bin 目录存在

      - name: Build Binaries
        run: |
          # 循环编译 amd64 和 arm64
          for arch in amd64 arm64; do
            GOOS=linux GOARCH=$arch go build -o "bin/dirstats-linux-$arch" ./cmd/dirstats/main.go
          done

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dirstats-binaries  # 单个 Artifact 包含所有架构文件
          path: bin/*
