name: Go Build

on:
  push:
    branches: ["main"]   # 触发分支
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: ["amd64", "arm64"]  # 定义目标架构
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4     # 检出代码

      - name: Set up Go
        uses: actions/setup-go@v5     # 安装 Go 环境
        with:
          go-version: "1.22"          # 指定 Go 版本

      - name: Cache Dependencies
        uses: actions/cache@v3        # 缓存 Go 模块加速构建
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Build
        env:
          GOOS: linux                 # 目标系统：Linux
          GOARCH: ${{ matrix.go-arch }}  # 从矩阵中获取架构
        run: |
          # 编译并指定输出文件名（示例：myapp-linux-amd64）
          go build -o cmd/dirstats/dss-linux-${{ matrix.go-arch }} ./...

      - name: Upload Artifact
        uses: actions/upload-artifact@v3  # 上传可执行文件
        with:
          name: executables
          path: bin/*
